#!/usr/bin/env bash

temp=$(mktemp -dp . "_test.XXXXX")

cd "$temp"
cp ../*.js .
for f in *.js; do mv "$f" "${f%.js}.mjs"; done

node --experimental-modules 'test.mjs' 2> >(grep -v '^(node:[[:digit:]]*) ExperimentalWarning: The ESM module loader is experimental.' >&2)

cd ..
rm -rf "$temp"
